services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tuemail@ejemplo.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/efs/traefik/letsencrypt:/letsencrypt"  # Volumen en EFS para certificados
    labels:
      - "traefik.enable=true"
    restart: always

  prometheus:
    command: ["sh", "-c", "sudo chown -R 1000:1000 /prometheus && mkdir -p /prometheus/data && exec prometheus --config.file=/prometheus/config/prometheus.yml --storage.tsdb.path=/prometheus/data"]
    build: ./Dockerfile.prometheus
    ports:
      - "9090:9090"
    volumes:
      - "/mnt/efs/prometheus:/prometheus"  # Volumen en EFS para datos de Prometheus
     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
    depends_on:
      otel-collector:
        condition: service_healthy
    restart: always

  myapp:
    image: python:3.10.12
    command: ["bash", "-c", "pip install --no-cache-dir -r requirements.txt && chmod +x ./src/main.py" ]
    entrypoint: ["python", "./src/main.py"]
    ports:
      - "8000:8000"
    volumes:
      - "/home/ubuntu/src:/mnt/efs/app"
    environment:
      - ENV=production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317  # Aquí configuramos la variable de entorno
    labels:
      - "traefik.enable=true"
    depends_on:
      otel-collector:
        condition: service_healthy  #
    restart: always

  otel-collector:
    build: ./Dockerfile.otel
    image: 
    ports:
      - "4317:4317"
    labels:
      - "traefik.enable=true"
    volumes:
      - "/mnt/efs/otel:/otel"
    healthcheck:   # 🔹 Healthcheck para asegurarse de que esté listo antes de que lo usen otros
      test: ["CMD", "curl", "-f", "http://localhost:4317"]
      interval: 10s
      retries: 5
    restart: always






