- name: Configure EC2 Node
  hosts: all
  become: yes
  tasks:

  # Tarea 1: Copia la configuración de OpenTelemetry al servidor
  - name: Copiar configuración de OpenTelemetry
    ansible.builtin.copy:
      src: ./config/otel-collector-config.yml
      dest: /mnt/efs/otel/conf/otel-collector-config.yml
      mode: "0644"

  # Tarea 2: Copia la configuración principal de Prometheus al servidor
  - name: Copiar configuración de Prometheus
    ansible.builtin.copy:
      src: ./config/prometheus.yml
      dest: /mnt/efs/prometheus/config/prometheus.yml
      mode: "0644"

  # Tarea 3: Copia el archivo de configuración web de Prometheus al servidor
  - name: Copiar configuración web de Prometheus
    ansible.builtin.copy:
      src: ./config/web.yml
      dest: /mnt/efs/prometheus/config/web.yml
      mode: "0644"

  # Tarea 4: Copia el código fuente de la aplicación al servidor
  - name: Copiar código fuente de la aplicación
    copy:
      src: ../../../app/src/
      dest: /home/ubuntu/src/
      mode: '0644'

  # Tarea 5: Copia el archivo de dependencias (requirements.txt) al servidor
  - name: Copiar archivo de dependencias
    copy:
      src: ../../../app/requirements.txt
      dest: /home/ubuntu/src/requirements.txt
      mode: '0644'

  # Tarea 6: Copia el Dockerfile de Prometheus al servidor
  - name: Copy Dockerfile
    copy:
      src: ./Dockerfile.prometheus
      dest: /home/ubuntu/Dockerfile.prometheus
      mode: '0644'

  # Tarea 7: Genera el archivo docker-compose.yml a partir de una plantilla
  - name: Generate docker-compose.yml from template
    template:
      src: ./docker-compose.yml.j2
      dest: /home/ubuntu/docker-compose.yml
      mode: '0644'

  # Añadir archivos de configuracion nagios a la imagen
  - name: Deploy Nagios Configuration
    copy:
      src: "nagios_config/{{ item }}"
      dest: "/mnt/efs/nagios:/usr/local/nagios/etc/{{ item }}"
      group: nagios
      mode: '0644'
    with_fileglob:
    - "nagios_config/*.cfg"

  # Tarea 8: Detiene los contenedores en ejecución usando Docker Compose
  - name: Stop running containers with Docker Compose
    command: docker compose down
    args:
      chdir: /home/ubuntu

  # Tarea 9: Inicia los contenedores en segundo plano usando Docker Compose
  - name: Start containers with Docker Compose
    command: docker compose up -d
    args:
      chdir: /home/ubuntu

  # Actualizar la contraseña nagios
  - name: Change Nagios username and password
    docker_container:
      name: nagios
      #Por defecto, el usuario es 'nagiosadmin' y la contraseña es 'nagios', mediante el comando de abajo se puede actualizar la contraseña
      command: /bin/bash -c "htpasswd -b /usr/local/nagios/etc/htpasswd.users {{ nagios_user }} {{ nagios_pass }}"
    become: true
    environment:
      nagios_user: "nagiosadmin"
      nagios_pass: "campusdual"

  # Reiniciar nagios para que la contraseña entre en efecto
  - name: Restart the Nagios
    command: docker restart nagios
