- name: Configure EC2 Node
  hosts: all
  become: yes
  tasks:

  # Tarea 1: Copia la configuración de OpenTelemetry al servidor
  - name: Copiar configuración de OpenTelemetry
    ansible.builtin.copy:
      src: ./config/otel-collector-config.yml
      dest: /mnt/efs/otel/conf/otel-collector-config.yml
      mode: "0644"

  # Tarea 2: Copia la configuración principal de Prometheus al servidor
  - name: Copiar configuración de Prometheus
    ansible.builtin.copy:
      src: ./config/prometheus.yml
      dest: /mnt/efs/prometheus/config/prometheus.yml
      mode: "0644"

  # Tarea 3: Copia el archivo de configuración web de Prometheus al servidor
  - name: Copiar configuración web de Prometheus
    ansible.builtin.copy:
      src: ./config/web.yml
      dest: /mnt/efs/prometheus/config/web.yml
      mode: "0644"

  # Tarea 4: Copia el código fuente de la aplicación al servidor
  - name: Copiar código fuente de la aplicación
    copy:
      src: ../../../app/src/
      dest: /home/ubuntu/src/
      mode: '0644'

  # Tarea 5: Copia el archivo de dependencias (requirements.txt) al servidor
  - name: Copiar archivo de dependencias
    copy:
      src: ../../../app/requirements.txt
      dest: /home/ubuntu/src/requirements.txt
      mode: '0644'

  # Tarea 6: Copia el Dockerfile de Prometheus al servidor
  - name: Copy Dockerfile
    copy:
      src: ./Dockerfile.prometheus
      dest: /home/ubuntu/Dockerfile.prometheus
      mode: '0644'

  # Tarea 7: Genera el archivo docker-compose.yml a partir de una plantilla
  - name: Generate docker-compose.yml from template
    template:
      src: ./docker-compose.yml.j2
      dest: /home/ubuntu/docker-compose.yml
      mode: '0644'

  # Añadir archivos de configuracion nagios a la imagen
  - name: Deploy Nagios Configuration
    copy:
      src: ./nagios_config/
      dest: /mnt/efs/nagios/nagios_config/
      mode: '0644'


  # Tarea 8: Detiene los contenedores en ejecución usando Docker Compose
  - name: Stop running containers with Docker Compose
    command: docker compose down
    args:
      chdir: /home/ubuntu

  # Tarea 9: Inicia los contenedores en segundo plano usando Docker Compose
  - name: Start containers with Docker Compose
    command: docker compose up -d
    args:
      chdir: /home/ubuntu
