- name: Configure Elasticsearch Nodes
  hosts: all
  become: yes
  vars:
    docker_compose_file: /home/ubuntu/docker-compose.yml.j2   # Ruta de destino para el archivo docker-compose.yml
    json_ip_name: /home/ubuntu/seed_hosts.json

  tasks:
    # Tarea 1: Copia el Dockerfile al host
    - name: Copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /home/ubuntu/Dockerfile
        mode: '0644'

    # Tarea 2: Obtiene la IP privada del host actual
    - name: Get private IP of the current host
      set_fact:
        PRIVATE_IP: "{{ ansible_default_ipv4.address }}"

    # Tarea 3: Genera el archivo docker-compose.yml a partir de la plantilla
    - name: Generate docker-compose.yml from template
      template:
        src: ./docker-compose.yml.j2     # Ruta de la plantilla
        dest: /home/ubuntu/docker-compose.yml    # Ruta de destino
        mode: '0644'

    # Tarea 4: Detiene Elasticsearch usando Docker Compose
    - name: Start Elasticsearch with Docker Compose
      command: docker compose down
      args:
        chdir: /home/ubuntu

    # Tarea 5: Inicia Elasticsearch en segundo plano utilizando Docker Compose
    - name: Start Elasticsearch with Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/ubuntu
